### ISSUE TITLE
YOUR_API_KEY and YOUR_INSTANCE_ID

### ISSUE THREAD

**Issue by xujw80** [SoundCTL/help#1]
Hello, 

Can you please let me know where to apply YOUR_API_KEY and YOUR_INSTANCE_ID? I am new to this API, want to give try. 

Thanks, 

XuJ

**Comment by streamer45** [comment]
Hello,

First of all if you haven't done it yet, you should create an instance by signing up at https://soundctl.io .
You can then find your instance ID and API key in your dashboard.

After that you can use those values to make requests to the API. Please refer to the [Documentation](https://github.com/SoundCTL/docs/blob/master/DOCS.md).
